# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b409ee5f52dcd3110e34fd5fa88ee1c4488a4fe2f22a17c47c6a7e61bbdd4d7378c0991256d8e430256738a262f7d53b224d8ebe9c6780ca5674c8f70428bf

test:
  secret_key_base: 9e6dc4101b6e6e51059d78b1e9709d4c341ca62737e2e16c9d071de4d83a4b532ec97da49e3eb6fdf7f0a52763a3347a1798de48f95cd981375ecd5c92567a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
